/*
    This file was automatically generated by Studio 3T.

    MongoDB Source Collection: `simulacroApp.tbl_asignaturas`

    Warnings about type conversion issues are stored as comments above the
    corresponding INSERT statement of each document.
*/


SET NAMES 'utf8' COLLATE 'utf8_general_ci';

DROP TABLE IF EXISTS `tbl_asignaturas`;
CREATE TABLE `tbl_asignaturas` (
    `__v` INTEGER,
    `_id` VARBINARY(12) NOT NULL,
    `created_at` DATETIME(3),
    `nombre` LONGTEXT,
    `universidad_id` VARBINARY(12),
    PRIMARY KEY (`_id`)
) CHARSET=utf8;

INSERT INTO `tbl_asignaturas` (`__v`, `_id`, `created_at`, `nombre`, `universidad_id`)
    VALUES
        (0, x'5AF31F42DADE1B4EE775BED4', '2018-05-09 14:17:38.947000', 'Razonamiento Matemático', x'5AF31CC4DADE1B4EE775BED2');
INSERT INTO `tbl_asignaturas` (`__v`, `_id`, `created_at`, `nombre`, `universidad_id`)
    VALUES
        (0, x'5AF65E44DADE1B4EE775BF2B', '2018-05-09 14:17:38.947000', 'Aritmética', x'5AF31CC4DADE1B4EE775BED2');
INSERT INTO `tbl_asignaturas` (`__v`, `_id`, `created_at`, `nombre`, `universidad_id`)
    VALUES
        (0, x'5AF66635DADE1B4EE775BF9F', '2018-05-09 14:17:38.947000', 'Álgebra', x'5AF31CC4DADE1B4EE775BED2');
INSERT INTO `tbl_asignaturas` (`__v`, `_id`, `created_at`, `nombre`, `universidad_id`)
    VALUES
        (0, x'5AF66F5BDADE1B4EE775C034', '2018-05-09 14:17:38.947000', 'Geometría', x'5AF31CC4DADE1B4EE775BED2');
INSERT INTO `tbl_asignaturas` (`__v`, `_id`, `created_at`, `nombre`, `universidad_id`)
    VALUES
        (0, x'5AF78B8FDADE1B4EE775C107', '2018-05-09 14:17:38.947000', 'Trigonometría', x'5AF31CC4DADE1B4EE775BED2');
INSERT INTO `tbl_asignaturas` (`__v`, `_id`, `created_at`, `nombre`, `universidad_id`)
    VALUES
        (0, x'5AF7942CDADE1B4EE775C17F', '2018-05-09 14:17:38.947000', 'Física', x'5AF31CC4DADE1B4EE775BED2');
INSERT INTO `tbl_asignaturas` (`__v`, `_id`, `created_at`, `nombre`, `universidad_id`)
    VALUES
        (0, x'5AF7A944DADE1B4EE775C203', '2018-05-09 14:17:38.947000', 'Química', x'5AF31CC4DADE1B4EE775BED2');
